name: dog
base: core24
version: 0.1.0
summary: dog
description: |
  dog is a command-line DNS client.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  dog:
    plugin: rust
    source: https://github.com/ogham/dog.git
    source-tag: v$CRAFT_PROJECT_VERSION
    build-packages:
      - libssl-dev
      - pkg-config

apps:
  dog:
    command: bin/dog
    plugs:
      - network
