name: dog
base: core20
version: 0.1.0
summary: dog
description: |
  dog is a command-line DNS client.

grade: stable
confinement: strict

parts:
  dog:
    plugin: rust
    source: https://github.com/ogham/dog/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    build-packages:
      - libssl-dev
      - build-essential
      - pkg-config

apps:
  dog:
    command: bin/dog
    plugs:
      - network
