name: dog
base: core20
adopt-info: dog
summary: dog
description: |
  dog is a command-line DNS client.

grade: stable
confinement: strict

parts:
  dog:
    plugin: rust
    source: https://github.com/ogham/dog.git
    build-packages:
      - libssl-dev
      - build-essential
      - pkg-config
    override-pull: |
      #set -x
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | cut -d- -f2-4 | tr -d 'v' )"

apps:
  dog:
    command: bin/dog
    plugs:
      - network
